### ISSUE TITLE
Unable to convert branches with multiple leafs (e.g. "x/D:y/D:z/D")

### ISSUE THREAD

**Issue by wdconinc** [diana-hep/root2avro#1]
I am unable to export ROOT trees in which the branches have multiple leafs. 

Test ROOT tree, generated by the following snipped:
```
TFile *f = new TFile("test.root","NEW");
TTree *t = new TTree("t", "");
double x[3];
t->Branch("r", &x, "x/D:y/D:z/D");
x[0] = 0;
x[1] = 1;
x[2] = 2; 
t->Fill(); 
x[0] = -10;
x[1] = 11;
x[2] = 12;
t->Fill(); 
x[0] = -100;
x[1] = -101;
x[2] = 102;
t->Fill();
x[0] = 20; 
x[1] = -21;
x[2] = -22;
t->Fill(); 
x[0] = 200;
x[1] = -201;
x[2] = 202;
t->Fill();
f->Write();
f->Close();
```
Next, attempt to convert to avro using `root2avro test.root t`.

**Expected result:**
Output such as
```
schema = {"type": "record",
          "name": "t",
          "fields": [{"name": "r.x", "type": "double"},
                     {"name": "r.y", "type": "double"},
                     {"name": "r.z", "type": "double"}]}

json = [{"r.x": 0, "r.y": 1, "r.z": 2},
        {"r.x": -10, "r.y": 11, "r.z": 12},
        {"r.x": -100, "r.y": -101, "r.z": 102},
        {"r.x": 20, "r.y": -21, "r.z": -22},
        {"r.x": 200, "r.y": -201, "r.z": 202}]
```

**Actual result:**
```
Error in <TTreeReaderValueBase::CreateProxy()>: The tree does not have a branch called x. You could check with TTree::Print() for available branches.
Segmentation fault (core dumped)
```

No workaround (short of rewriting 200 TB of existing trees). I'd be happy to test, debug, or even write some code on my own to figure this out, but a pointer or two might make me more efficient in this new codebase.

**Comment by jpivarski** [comment]
Sorry for the confusion— this is an old project, our first attempt to get data into Spark, but we had more success with reimplementations of ROOT I/O in other languages, such as spark-root (Java/Scala) and uproot (Python).

In the year since I developed root2avro, I also learned more about the structure of ROOT files and how to do these transformations in more generality. Multiple-leaf branches is a feature I just implemented in uproot— would you be interested in trying this transformation there?

That is, if your interest is producing Avro files, we can do a full-speed pipeline with uproot and pyavroc. If your goal is to get the data into some particular system, where Avro is a means to an end, let me know what you're trying to do and I'll see if we can handle your situation.

Sorry for missing this earlier— I found out that I'm not automatically "watching" these repos, and I was doing a scan of all of them, looking for issues.
